/* PlantPlanet - plantData.js */
const PLANT_DATABASE = [
  // --- 🌲 樹木 (Trees) ---
  {
    id: 'sugi',
    name: '杉の木',
    icon: '🌲',
    category: 'tree',
    desc: '真っ直ぐ高く育つ日本を代表する針葉樹。',
    growthSpeed: 0.8,
    maxHeight: 280,
    trunkColor: '#5c3a21',
    leafColor: '#1e5e3a',
    leafType: 'needle', // 針葉
    branchAngle: 0.6,
    maxBranchDepth: 5,
    fruitType: 'none',
    rootDepth: 100
  },
  {
    id: 'sakura',
    name: '桜 (ソメイヨシノ)',
    icon: '🌸',
    category: 'tree',
    desc: '満開になると美しいピンクの花弁を咲かせる巨木。',
    growthSpeed: 0.7,
    maxHeight: 240,
    trunkColor: '#4a2e1b',
    leafColor: '#2e7d32',
    flowerColor: '#ffb7c5',
    leafType: 'oval',
    branchAngle: 0.8,
    maxBranchDepth: 5,
    flowerStage: 0.6,
    rootDepth: 90
  },
  {
    id: 'matsu',
    name: '松の木',
    icon: '🎍',
    category: 'tree',
    desc: '曲がりくねった味わい深い幹と青々とした松葉。',
    growthSpeed: 0.6,
    maxHeight: 200,
    trunkColor: '#3d2516',
    leafColor: '#1b4d3e',
    leafType: 'needle',
    branchAngle: 0.9,
    crookedness: 0.35,
    maxBranchDepth: 4,
    rootDepth: 110
  },
  {
    id: 'yashi',
    name: '椰子の木 (ヤシ)',
    icon: '🌴',
    category: 'tree',
    desc: '南国の風にそよぐ長い幹と大きな椰子の実。',
    growthSpeed: 0.9,
    maxHeight: 250,
    trunkColor: '#8d6e63',
    leafColor: '#2e7d32',
    leafType: 'palm',
    branchAngle: 1.2,
    maxBranchDepth: 1,
    fruitType: 'coconut',
    fruitColor: '#4e342e',
    fruitStage: 0.8,
    rootDepth: 70
  },
  {
    id: 'take',
    name: '竹 (タケ)',
    icon: '🎋',
    category: 'tree',
    desc: '節を持ち、一直線に爆発的なスピードで伸びる。',
    growthSpeed: 2.2,
    maxHeight: 320,
    trunkColor: '#43a047',
    leafColor: '#66bb6a',
    leafType: 'bamboo',
    branchAngle: 0.5,
    maxBranchDepth: 3,
    rootDepth: 80
  },
  {
    id: 'kaede',
    name: 'カエデ (モミジ)',
    icon: '🍁',
    category: 'tree',
    desc: '紅葉すると真っ赤に染まる美しい楓の木。',
    growthSpeed: 0.75,
    maxHeight: 190,
    trunkColor: '#5d4037',
    leafColor: '#e53935',
    leafType: 'maple',
    branchAngle: 0.75,
    maxBranchDepth: 5,
    rootDepth: 80
  },
  {
    id: 'yanagi',
    name: 'しだれ柳',
    icon: '🌿',
    category: 'tree',
    desc: '優雅に地面に向かって枝垂れる緑の葉。',
    growthSpeed: 0.85,
    maxHeight: 210,
    trunkColor: '#4e342e',
    leafColor: '#7cb342',
    leafType: 'willow',
    branchAngle: 1.4,
    droopiness: 0.8,
    maxBranchDepth: 4,
    rootDepth: 95
  },
  {
    id: 'ginko',
    name: 'イチョウ (銀杏)',
    icon: '🟡',
    category: 'tree',
    desc: '扇型の黄金色の葉を茂らせる歴史ある大木。',
    growthSpeed: 0.7,
    maxHeight: 260,
    trunkColor: '#5d4037',
    leafColor: '#fbc02d',
    leafType: 'ginkgo',
    branchAngle: 0.65,
    maxBranchDepth: 5,
    rootDepth: 100
  },
  {
    id: 'olive',
    name: 'オリーブの木',
    icon: '🫒',
    category: 'tree',
    desc: '銀緑色の葉と美味しいオリーブの実。',
    growthSpeed: 0.65,
    maxHeight: 170,
    trunkColor: '#6d4c41',
    leafColor: '#78909c',
    leafType: 'oval',
    branchAngle: 0.8,
    maxBranchDepth: 4,
    fruitType: 'olive',
    fruitColor: '#33691e',
    fruitStage: 0.7,
    rootDepth: 75
  },
  {
    id: 'sequoia',
    name: '世界樹 (セコイア)',
    icon: '🌲',
    category: 'tree',
    desc: '天空まで届く太く巨大な幹を持つ神秘の巨木。',
    growthSpeed: 0.5,
    maxHeight: 450,
    trunkColor: '#3e2723',
    leafColor: '#004d40',
    leafType: 'needle',
    branchAngle: 0.6,
    trunkWidthMult: 2.5,
    maxBranchDepth: 6,
    rootDepth: 180
  },
  {
    id: 'gajumaru',
    name: 'ガジュマル',
    icon: '🌳',
    category: 'tree',
    desc: '気根を複雑に絡ませて育つ幸運を呼ぶ木。',
    growthSpeed: 0.6,
    maxHeight: 180,
    trunkColor: '#4e342e',
    leafColor: '#1b5e20',
    leafType: 'oval',
    aerialRoots: true,
    branchAngle: 0.9,
    maxBranchDepth: 5,
    rootDepth: 120
  },
  {
    id: 'buna',
    name: 'ブナの木',
    icon: '🌳',
    category: 'tree',
    desc: '白い美しい幹肌と豊穣の森を作る広葉樹。',
    growthSpeed: 0.7,
    maxHeight: 230,
    trunkColor: '#8d6e63',
    leafColor: '#33691e',
    leafType: 'oval',
    branchAngle: 0.7,
    maxBranchDepth: 5,
    rootDepth: 90
  },
  {
    id: 'baobab',
    name: 'バオバブの木',
    icon: '🪵',
    category: 'tree',
    desc: '徳利のような極太の幹に水分を蓄える不思議な大木。',
    growthSpeed: 0.55,
    maxHeight: 220,
    trunkColor: '#795548',
    leafColor: '#558b2f',
    leafType: 'round',
    trunkWidthMult: 3.2,
    branchAngle: 0.9,
    maxBranchDepth: 3,
    rootDepth: 140
  },
  {
    id: 'momi',
    name: 'モミの木',
    icon: '🎄',
    category: 'tree',
    desc: 'きれいな円錐形に育つクリスマスツリーの木。',
    growthSpeed: 0.75,
    maxHeight: 250,
    trunkColor: '#4e342e',
    leafColor: '#00695c',
    leafType: 'needle',
    branchAngle: 0.55,
    maxBranchDepth: 5,
    rootDepth: 85
  },
  {
    id: 'eucalyptus',
    name: 'ユーカリ',
    icon: '🌿',
    category: 'tree',
    desc: '爽やかな香りを放つ銀青色の葉を持つ樹木。',
    growthSpeed: 1.1,
    maxHeight: 270,
    trunkColor: '#a1887f',
    leafColor: '#4db6ac',
    leafType: 'oval',
    branchAngle: 0.65,
    maxBranchDepth: 4,
    rootDepth: 105
  },

  // --- 🍅 野菜・果物 (Crops & Fruits) ---
  {
    id: 'tomato',
    name: 'トマト',
    icon: '🍅',
    category: 'crop',
    desc: '赤く熟した甘い実をたくさんつける人気野菜。',
    growthSpeed: 1.2,
    maxHeight: 120,
    trunkColor: '#558b2f',
    leafColor: '#33691e',
    flowerColor: '#ffee58',
    leafType: 'jagged',
    branchAngle: 0.7,
    maxBranchDepth: 3,
    flowerStage: 0.4,
    fruitType: 'tomato',
    fruitColor: '#e53935',
    fruitStage: 0.65,
    rootDepth: 50
  },
  {
    id: 'ichigo',
    name: 'イチゴ (草苺)',
    icon: '🍓',
    category: 'crop',
    desc: '背は低いが真っ赤で可愛らしい果実をつける。',
    growthSpeed: 1.3,
    maxHeight: 60,
    trunkColor: '#689f38',
    leafColor: '#388e3c',
    flowerColor: '#ffffff',
    leafType: 'strawberry',
    branchAngle: 0.8,
    maxBranchDepth: 2,
    flowerStage: 0.35,
    fruitType: 'strawberry',
    fruitColor: '#ff1744',
    fruitStage: 0.6,
    rootDepth: 35
  },
  {
    id: 'ringo',
    name: 'リンゴの木',
    icon: '🍎',
    category: 'crop',
    desc: 'たわわに実る真っ赤なリンゴ。',
    growthSpeed: 0.8,
    maxHeight: 180,
    trunkColor: '#5d4037',
    leafColor: '#2e7d32',
    flowerColor: '#f8bbd0',
    leafType: 'oval',
    branchAngle: 0.75,
    maxBranchDepth: 4,
    flowerStage: 0.45,
    fruitType: 'apple',
    fruitColor: '#d50000',
    fruitStage: 0.7,
    rootDepth: 80
  },
  {
    id: 'suika',
    name: 'スイカ (西瓜)',
    icon: '🍉',
    category: 'crop',
    desc: 'ツタを伸ばして地面に大きな縞模様の実をならせる。',
    growthSpeed: 1.1,
    maxHeight: 50,
    trunkColor: '#689f38',
    leafColor: '#2e7d32',
    flowerColor: '#ffd600',
    leafType: 'vine',
    branchAngle: 1.3,
    maxBranchDepth: 3,
    vineGrowth: true,
    fruitType: 'watermelon',
    fruitColor: '#1b5e20',
    fruitStage: 0.7,
    rootDepth: 45
  },
  {
    id: 'meron',
    name: 'メロン',
    icon: '🍈',
    category: 'crop',
    desc: '網目模様の高級で甘い果実をつけるツタ植物。',
    growthSpeed: 1.0,
    maxHeight: 55,
    trunkColor: '#7cb342',
    leafColor: '#558b2f',
    flowerColor: '#ffea00',
    leafType: 'vine',
    branchAngle: 1.2,
    maxBranchDepth: 3,
    vineGrowth: true,
    fruitType: 'melon',
    fruitColor: '#aed581',
    fruitStage: 0.7,
    rootDepth: 45
  },
  {
    id: 'toumorokoshi',
    name: 'トウモロコシ',
    icon: '🌽',
    category: 'crop',
    desc: '高くスッと伸びて黄色い粒の詰まった実をつける。',
    growthSpeed: 1.4,
    maxHeight: 160,
    trunkColor: '#7cb342',
    leafColor: '#558b2f',
    leafType: 'corn',
    branchAngle: 0.4,
    maxBranchDepth: 2,
    fruitType: 'corn',
    fruitColor: '#ffb300',
    fruitStage: 0.6,
    rootDepth: 60
  },
  {
    id: 'ninjin',
    name: 'ニンジン',
    icon: '🥕',
    category: 'crop',
    desc: '地上にはフサフサの葉、地中にはオレンジ色の豊かな根。',
    growthSpeed: 1.2,
    maxHeight: 80,
    trunkColor: '#81c784',
    leafColor: '#388e3c',
    leafType: 'fern',
    branchAngle: 0.5,
    maxBranchDepth: 2,
    rootFruitType: 'carrot',
    rootFruitColor: '#ff6d00',
    rootDepth: 75
  },
  {
    id: 'kabocha',
    name: 'カボチャ',
    icon: '🎃',
    category: 'crop',
    desc: '地面を這うようにツタを広げ、どっしりした橙色の実をつける。',
    growthSpeed: 1.0,
    maxHeight: 55,
    trunkColor: '#689f38',
    leafColor: '#33691e',
    flowerColor: '#ffab00',
    leafType: 'vine',
    branchAngle: 1.4,
    vineGrowth: true,
    maxBranchDepth: 3,
    fruitType: 'pumpkin',
    fruitColor: '#ff6f00',
    fruitStage: 0.7,
    rootDepth: 50
  },
  {
    id: 'nasu',
    name: 'ナス (茄子)',
    icon: '🍆',
    category: 'crop',
    desc: '鮮やかな紫色の花とツヤツヤした紫の実。',
    growthSpeed: 1.1,
    maxHeight: 110,
    trunkColor: '#4a148c',
    leafColor: '#2e7d32',
    flowerColor: '#ab47bc',
    leafType: 'oval',
    branchAngle: 0.7,
    maxBranchDepth: 3,
    flowerStage: 0.4,
    fruitType: 'eggplant',
    fruitColor: '#4a148c',
    fruitStage: 0.65,
    rootDepth: 50
  },
  {
    id: 'budou',
    name: 'ブドウ (葡萄)',
    icon: '🍇',
    category: 'crop',
    desc: '棚や木にツタを絡ませ、紫色の房状の実をつける。',
    growthSpeed: 0.9,
    maxHeight: 140,
    trunkColor: '#5d4037',
    leafColor: '#43a047',
    leafType: 'grape',
    branchAngle: 1.1,
    maxBranchDepth: 4,
    fruitType: 'grape',
    fruitColor: '#6a1b9a',
    fruitStage: 0.7,
    rootDepth: 70
  },
  {
    id: 'momo',
    name: '桃の木',
    icon: '🍑',
    category: 'crop',
    desc: 'ピンクの花を咲かせたあと、みずみずしい桃が実る。',
    growthSpeed: 0.8,
    maxHeight: 175,
    trunkColor: '#5d4037',
    leafColor: '#388e3c',
    flowerColor: '#f48fb1',
    leafType: 'oval',
    branchAngle: 0.75,
    maxBranchDepth: 4,
    flowerStage: 0.4,
    fruitType: 'peach',
    fruitColor: '#ff80ab',
    fruitStage: 0.7,
    rootDepth: 75
  },
  {
    id: 'mikan',
    name: 'ミカンの木',
    icon: '🍊',
    category: 'crop',
    desc: '常緑の葉と鮮やかなオレンジ色の柑橘。',
    growthSpeed: 0.8,
    maxHeight: 165,
    trunkColor: '#4e342e',
    leafColor: '#1b5e20',
    flowerColor: '#ffffff',
    leafType: 'oval',
    branchAngle: 0.8,
    maxBranchDepth: 4,
    flowerStage: 0.4,
    fruitType: 'orange',
    fruitColor: '#ff9100',
    fruitStage: 0.7,
    rootDepth: 70
  },
  {
    id: 'banana',
    name: 'バナナの木',
    icon: '🍌',
    category: 'crop',
    desc: '超巨大な葉を広げ、大きな房状のバナナを実らせる。',
    growthSpeed: 1.3,
    maxHeight: 230,
    trunkColor: '#827717',
    leafColor: '#7cb342',
    leafType: 'banana',
    branchAngle: 0.9,
    maxBranchDepth: 2,
    fruitType: 'banana',
    fruitColor: '#ffd600',
    fruitStage: 0.75,
    rootDepth: 80
  },
  {
    id: 'pineapple',
    name: 'パイナップル',
    icon: '🍍',
    category: 'crop',
    desc: 'トゲトゲした葉の真ん中に大きな甘い実が育つ。',
    growthSpeed: 0.85,
    maxHeight: 90,
    trunkColor: '#558b2f',
    leafColor: '#33691e',
    leafType: 'spiky',
    branchAngle: 0.8,
    maxBranchDepth: 2,
    fruitType: 'pineapple',
    fruitColor: '#ffab00',
    fruitStage: 0.7,
    rootDepth: 55
  },
  {
    id: 'blueberry',
    name: 'ブルーベリー',
    icon: '🫐',
    category: 'crop',
    desc: '低木に可愛い青紫色のベリーが鈴なりになる。',
    growthSpeed: 0.9,
    maxHeight: 110,
    trunkColor: '#6d4c41',
    leafColor: '#388e3c',
    flowerColor: '#e1bee7',
    leafType: 'oval',
    branchAngle: 0.85,
    maxBranchDepth: 4,
    fruitType: 'blueberry',
    fruitColor: '#303f9f',
    fruitStage: 0.65,
    rootDepth: 45
  },

  // --- 🌸 花卉・草本 (Flowers & Herbs) ---
  {
    id: 'himawari',
    name: 'ヒマワリ (向日葵)',
    icon: '🌻',
    category: 'flower',
    desc: '太陽に向かって高く伸びる大輪の黄色い花。',
    growthSpeed: 1.4,
    maxHeight: 180,
    trunkColor: '#689f38',
    leafColor: '#33691e',
    flowerColor: '#ffc107',
    leafType: 'heart',
    branchAngle: 0.3,
    maxBranchDepth: 1,
    flowerStage: 0.5,
    rootDepth: 65
  },
  {
    id: 'tulip',
    name: 'チューリップ',
    icon: '🌷',
    category: 'flower',
    desc: '球根から可愛らしいカップ状の花を咲かせる。',
    growthSpeed: 1.5,
    maxHeight: 70,
    trunkColor: '#7cb342',
    leafColor: '#558b2f',
    flowerColor: '#e91e63',
    leafType: 'tulip',
    branchAngle: 0.2,
    maxBranchDepth: 1,
    flowerStage: 0.5,
    rootDepth: 40
  },
  {
    id: 'bara',
    name: 'バラ (薔薇)',
    icon: '🌹',
    category: 'flower',
    desc: 'トゲのある茎と気品溢れる香りの赤い花びら。',
    growthSpeed: 0.9,
    maxHeight: 120,
    trunkColor: '#33691e',
    leafColor: '#1b5e20',
    flowerColor: '#d50000',
    leafType: 'rose',
    branchAngle: 0.7,
    maxBranchDepth: 3,
    thorns: true,
    flowerStage: 0.45,
    rootDepth: 55
  },
  {
    id: 'ajisai',
    name: 'アジサイ (紫陽花)',
    icon: '🪻',
    category: 'flower',
    desc: '雨が似合う手毬状のグラデーション花。',
    growthSpeed: 1.0,
    maxHeight: 110,
    trunkColor: '#5d4037',
    leafColor: '#2e7d32',
    flowerColor: '#42a5f5',
    leafType: 'oval',
    branchAngle: 0.8,
    maxBranchDepth: 4,
    flowerStage: 0.4,
    rootDepth: 50
  },
  {
    id: 'fuji',
    name: '藤 (フジ)',
    icon: '🪻',
    category: 'flower',
    desc: '紫色の花房が滝のように美しく垂れ下がる。',
    growthSpeed: 0.8,
    maxHeight: 160,
    trunkColor: '#4e342e',
    leafColor: '#558b2f',
    flowerColor: '#9c27b0',
    leafType: 'oval',
    branchAngle: 1.2,
    droopiness: 0.7,
    maxBranchDepth: 4,
    flowerStage: 0.5,
    rootDepth: 75
  },
  {
    id: 'lavender',
    name: 'ラベンダー',
    icon: '🪻',
    category: 'flower',
    desc: 'リラックス効果のある香りと紫色の小さな花穂。',
    growthSpeed: 1.2,
    maxHeight: 85,
    trunkColor: '#689f38',
    leafColor: '#78909c',
    flowerColor: '#7b1fa2',
    leafType: 'needle',
    branchAngle: 0.4,
    maxBranchDepth: 3,
    flowerStage: 0.4,
    rootDepth: 45
  },
  {
    id: 'tampopo',
    name: 'タンポポ (蒲公英)',
    icon: '🌼',
    category: 'flower',
    desc: '黄色い花が咲いた後、綿毛になって風に舞う。',
    growthSpeed: 1.6,
    maxHeight: 50,
    trunkColor: '#81c784',
    leafColor: '#388e3c',
    flowerColor: '#ffee58',
    seedFluff: true,
    leafType: 'jagged',
    branchAngle: 0.3,
    maxBranchDepth: 1,
    flowerStage: 0.4,
    rootDepth: 60
  },
  {
    id: 'asagao',
    name: '朝顔 (アサガオ)',
    icon: '🌺',
    category: 'flower',
    desc: '朝一番にラッパ状の涼しげな花を咲かせるツタ。',
    growthSpeed: 1.3,
    maxHeight: 130,
    trunkColor: '#689f38',
    leafColor: '#43a047',
    flowerColor: '#1e88e5',
    leafType: 'heart',
    branchAngle: 1.1,
    vineGrowth: true,
    maxBranchDepth: 3,
    flowerStage: 0.4,
    rootDepth: 45
  },
  {
    id: 'suzuran',
    name: 'スズラン (鈴蘭)',
    icon: '🔔',
    category: 'flower',
    desc: '白い可憐な鈴のような小さな花をつける。',
    growthSpeed: 1.3,
    maxHeight: 45,
    trunkColor: '#7cb342',
    leafColor: '#388e3c',
    flowerColor: '#ffffff',
    leafType: 'tulip',
    branchAngle: 0.3,
    maxBranchDepth: 1,
    flowerStage: 0.45,
    rootDepth: 35
  },
  {
    id: 'marigold',
    name: 'マリーゴールド',
    icon: '🌼',
    category: 'flower',
    desc: '鮮やかなオレンジ色のフリル状の花弁が長く咲く。',
    growthSpeed: 1.3,
    maxHeight: 65,
    trunkColor: '#689f38',
    leafColor: '#2e7d32',
    flowerColor: '#ff6f00',
    leafType: 'fern',
    branchAngle: 0.6,
    maxBranchDepth: 3,
    flowerStage: 0.4,
    rootDepth: 40
  },
  {
    id: 'cosmos',
    name: 'コスモス (秋桜)',
    icon: '🌸',
    category: 'flower',
    desc: '細い茎を風になびかせて咲く秋の風物詩。',
    growthSpeed: 1.4,
    maxHeight: 120,
    trunkColor: '#7cb342',
    leafColor: '#558b2f',
    flowerColor: '#f48fb1',
    leafType: 'fern',
    branchAngle: 0.5,
    maxBranchDepth: 3,
    flowerStage: 0.45,
    rootDepth: 50
  },
  {
    id: 'yuri',
    name: 'カサブランカ (百合)',
    icon: '🪷',
    category: 'flower',
    desc: '大きく開く大輪の白い花と甘く豊かな香り。',
    growthSpeed: 1.1,
    maxHeight: 110,
    trunkColor: '#7cb342',
    leafColor: '#2e7d32',
    flowerColor: '#ffffff',
    leafType: 'tulip',
    branchAngle: 0.3,
    maxBranchDepth: 2,
    flowerStage: 0.5,
    rootDepth: 55
  },
  {
    id: 'nemophila',
    name: 'ネモフィラ',
    icon: '🩵',
    category: 'flower',
    desc: '一面を澄み渡る青空の色に染める可憐な小花。',
    growthSpeed: 1.5,
    maxHeight: 40,
    trunkColor: '#81c784',
    leafColor: '#4caf50',
    flowerColor: '#29b6f6',
    leafType: 'round',
    branchAngle: 0.7,
    maxBranchDepth: 2,
    flowerStage: 0.35,
    rootDepth: 30
  },
  {
    id: 'carnation',
    name: 'カーネーション',
    icon: '💐',
    category: 'flower',
    desc: '感謝の気持ちを象徴するフリル重なる赤い花びら。',
    growthSpeed: 1.2,
    maxHeight: 75,
    trunkColor: '#7cb342',
    leafColor: '#388e3c',
    flowerColor: '#e91e63',
    leafType: 'needle',
    branchAngle: 0.5,
    maxBranchDepth: 2,
    flowerStage: 0.4,
    rootDepth: 40
  },
  {
    id: 'hasu',
    name: 'ハス (蓮)',
    icon: '🪷',
    category: 'flower',
    desc: '清らかな美しい大きな花と丸い葉。',
    growthSpeed: 1.0,
    maxHeight: 90,
    trunkColor: '#689f38',
    leafColor: '#2e7d32',
    flowerColor: '#f06292',
    leafType: 'lotus',
    branchAngle: 0.2,
    maxBranchDepth: 1,
    flowerStage: 0.45,
    rootDepth: 65
  },
  {
    id: 'shibafu',
    name: '緑の芝生 (シバ)',
    icon: '🌱',
    category: 'flower',
    desc: '一面に青々と広がる密な草むらを作る。',
    growthSpeed: 2.0,
    maxHeight: 30,
    trunkColor: '#7cb342',
    leafColor: '#43a047',
    leafType: 'grass',
    branchAngle: 0.3,
    maxBranchDepth: 2,
    rootDepth: 30
  },
  {
    id: 'koke',
    name: 'スギゴケ (苔)',
    icon: '🟩',
    category: 'flower',
    desc: 'しっとりと土を覆う風情ある緑の絨毯。',
    growthSpeed: 1.8,
    maxHeight: 20,
    trunkColor: '#33691e',
    leafColor: '#2e7d32',
    leafType: 'moss',
    branchAngle: 0.4,
    maxBranchDepth: 2,
    rootDepth: 20
  },

  // --- 🌵 珍種・多肉・ファンタジー (Special & Fantasy) ---
  {
    id: 'saboten',
    name: 'サボテン (仙人掌)',
    icon: '🌵',
    category: 'special',
    desc: '乾燥に耐えるトゲだらけの肉厚な茎と鮮やかな花。',
    growthSpeed: 0.6,
    maxHeight: 140,
    trunkColor: '#2e7d32',
    leafColor: '#1b5e20',
    flowerColor: '#ff4081',
    leafType: 'cactus',
    thorns: true,
    branchAngle: 0.8,
    maxBranchDepth: 3,
    flowerStage: 0.6,
    rootDepth: 70
  },
  {
    id: 'taniku',
    name: '多肉植物 (エケベリア)',
    icon: '🪴',
    category: 'special',
    desc: 'バラの花のようにぷっくりとした肉厚の葉を重ねる。',
    growthSpeed: 0.8,
    maxHeight: 45,
    trunkColor: '#689f38',
    leafColor: '#80cbc4',
    flowerColor: '#ff80ab',
    leafType: 'succulent',
    branchAngle: 0.4,
    maxBranchDepth: 1,
    rootDepth: 35
  },
  {
    id: 'hikari_kinoko',
    name: '発光キノコ (月夜茸)',
    icon: '🍄',
    category: 'special',
    desc: '暗闇で幻想的な青緑色の光を放つ不思議な菌類。',
    growthSpeed: 1.6,
    maxHeight: 70,
    trunkColor: '#b2dfdb',
    leafColor: '#00bfa5',
    glowing: true,
    glowColor: '#00e676',
    leafType: 'mushroom',
    branchAngle: 0.4,
    maxBranchDepth: 2,
    rootDepth: 40
  },
  {
    id: 'doku_kinoko',
    name: 'ベニテングタケ (毒キノコ)',
    icon: '🍄',
    category: 'special',
    desc: '真っ赤な傘に白い斑点模様の怪しいキノコ。',
    growthSpeed: 1.5,
    maxHeight: 65,
    trunkColor: '#fff9c4',
    leafColor: '#ff1744',
    leafType: 'mushroom',
    branchAngle: 0.4,
    maxBranchDepth: 2,
    rootDepth: 35
  },
  {
    id: 'haetori',
    name: 'ハエトリソウ (食虫植物)',
    icon: '🪴',
    category: 'special',
    desc: 'パックリ開いた葉で獲物を捕らえる珍しい植物。',
    growthSpeed: 1.0,
    maxHeight: 60,
    trunkColor: '#558b2f',
    leafColor: '#d50000',
    leafType: 'flytrap',
    branchAngle: 0.6,
    maxBranchDepth: 2,
    rootDepth: 40
  },
  {
    id: 'magic_bean',
    name: 'ジャックの魔法の豆',
    icon: '🫘',
    category: 'special',
    desc: '雲を突き抜けて天空まで一気に伸びる不思議な豆の木。',
    growthSpeed: 2.5,
    maxHeight: 500,
    trunkColor: '#33691e',
    leafColor: '#7cb342',
    leafType: 'heart',
    vineGrowth: true,
    branchAngle: 0.7,
    maxBranchDepth: 6,
    rootDepth: 160
  },
  {
    id: 'suishosou',
    name: '水晶草 (クリスタルグラス)',
    icon: '💎',
    category: 'special',
    desc: '透明な水晶の結晶のような茎と葉を持つ鉱物植物。',
    growthSpeed: 0.7,
    maxHeight: 85,
    trunkColor: '#b388ff',
    leafColor: '#80d8ff',
    glowing: true,
    glowColor: '#80d8ff',
    leafType: 'crystal',
    branchAngle: 0.5,
    maxBranchDepth: 3,
    rootDepth: 50
  },
  {
    id: 'golden_rose',
    name: '黄金の薔薇 (ゴールデンローズ)',
    icon: '🌟',
    category: 'special',
    desc: '黄金色に神々しく輝く伝説の薔薇。',
    growthSpeed: 0.75,
    maxHeight: 130,
    trunkColor: '#ffb300',
    leafColor: '#ffd54f',
    flowerColor: '#ffd700',
    glowing: true,
    glowColor: '#ffe082',
    leafType: 'rose',
    thorns: true,
    branchAngle: 0.7,
    maxBranchDepth: 3,
    flowerStage: 0.45,
    rootDepth: 65
  }
];
